#sensio_framework_extra:
#    router:
#        annotations: false
sensio_framework_extra:
    #router:      { annotations: true } # Deprecated; use routing annotations of Symfony core instead
    router:      { annotations: false } #https://github.com/symfony/demo/issues/786
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false } # Defaults to true if the PSR-7 bridge is installed

