parameters:
  deidentifier.sitename: deidentifier

twig:
    globals:
        deidentifier_sitename: '%deidentifier.sitename%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                                    # fetching services directly from the container via $container->get() won't work.
                                    # The best practice is to be explicit about your dependencies anyway.
#    oleg_deidentifier.example:
#        class: App\DeidentifierBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    deidentifier_authentication_handler:
        class: App\DeidentifierBundle\Security\Authentication\DeidentifierLoginSuccessHandler
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    deidentifier_role_voter:
        class: App\DeidentifierBundle\Security\Voter\DeidentifierRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    deidentifier_permission_voter:
        class: App\DeidentifierBundle\Security\Voter\DeidentifierPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }
