parameters:

    vacreq.sitename: vacreq
    vacreq.uploadpath:


twig:
    globals:
        vacreq_sitename: '%vacreq.sitename%'
        #service
        vacreq_util: "@vacreq_util"


services:
    _defaults: { public: true }

    vacreq_authentication_handler:
        class: Oleg\VacReqBundle\Security\Authentication\VacReqLoginSuccessHandler
        arguments:  ["@service_container", "@doctrine.orm.entity_manager"]

    vacreq_role_voter:
        class: Oleg\VacReqBundle\Security\Voter\VacReqRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    vacreq_permission_voter:
        class: Oleg\VacReqBundle\Security\Voter\VacReqPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    vacreq_util:
        class: Oleg\VacReqBundle\Util\VacReqUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker", "@service_container"]

    vacreq_import_data:
        class: Oleg\VacReqBundle\Util\VacReqImportData
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    vacreq_awaycalendar_listener:
        class: Oleg\VacReqBundle\EventListener\CalendarEventListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }