
main_common_home:
    path:      /
    defaults:  { _controller: OlegUserdirectoryBundle:Home:mainCommonHome }
    schemes:  ['%connection_channel%']

main_under_construction:
    path:      /under-construction
    defaults:  { _controller: OlegUserdirectoryBundle:Home:underConstruction }
    schemes:  ['%connection_channel%']

#order is important: base bundle userdirectory must be the last one
oleg_deidentifier:
    resource: "@OlegDeidentifierBundle/Controller/"
    type:     annotation
    prefix:   /deidentifier
    schemes:  ['%connection_channel%']

oleg_fellapp:
    resource: "@OlegFellAppBundle/Controller/"
    type:     annotation
    prefix:   /fellowship-applications
    schemes:  ['%connection_channel%']

oleg_vacreq:
    resource: "@OlegVacReqBundle/Controller/"
    type:     annotation
    prefix:   /vacation-request
    schemes:  ['%connection_channel%']

oleg_calllog:
    resource: "@OlegCallLogBundle/Controller/"
    type:     annotation
    prefix:   /call-log-book
    schemes:  ['%connection_channel%']

oleg_orderform:
    resource: "@OlegOrderformBundle/Controller/"
    type:     annotation
    prefix:   /scan
    schemes:  ['%connection_channel%']

oleg_translationalresearch:
    resource: "@OlegTranslationalResearchBundle/Controller/"
    type:     annotation
    prefix:   /translational-research
    schemes:  ['%connection_channel%']

oleg_userdirectory:
    resource: "@OlegUserdirectoryBundle/Controller/"
    type:     annotation
    prefix:   /directory
    schemes:  ['%connection_channel%']


adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
    prefix:   /vacation-request
    schemes:  ['%connection_channel%']


#acme_demo:
#    resource: "@AcmeDemoBundle/Controller/"
#    type:     annotation
#    prefix:   /demo

oleg_testpage:
    path: /directory/testpage
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'OlegUserdirectoryBundle:Default:testpage.html.twig'

fellapp_instructions:
    path: /fellowship-applications/instructions-to-change-import-interval
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'OlegFellAppBundle:Instructions:taskSchedulerWindows.html.twig'

#login and logout routes

#logout - is a general logout route used in SessionIdleHandler and MaintenanceListener
logout:
    path:   /directory/logout
    schemes:  ['%connection_channel%']
login:
    path:   /directory/login
    schemes:  ['%connection_channel%']

scan_login_check:
    path:   /scan/login_check
scan_logout:
    path:   /scan/logout

employees_login_check:
    path:   /directory/login_check
    schemes:  ['%connection_channel%']
employees_logout:
    path:   /directory/logout
    schemes:  ['%connection_channel%']

fellapp_login_check:
    path:   /fellowship-applications/login_check
fellapp_logout:
    path:   /fellowship-applications/logout

deidentifier_login_check:
    path:   /deidentifier/login_check
deidentifier_logout:
    path:   /deidentifier/logout

vacreq_login_check:
    path:   /vacation-request/login_check
vacreq_logout:
    path:   /vacation-request/logout

calllog_login_check:
    path:   /call-log-book/login_check
calllog_logout:
    path:   /call-log-book/logout

translationalresearch_login_check:
    path:   /translational-research/login_check
translationalresearch_logout:
    path:   /translational-research/logout

#fos user bundle
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /group


#OneupUploaderBundle  file uploader
oneup_uploader:
    resource: .
    type: uploader

#TreeBrowserBundle
#cmf_tree:
#    resource: .
#    type: 'cmf_tree'

#FOSJsRoutingBundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

